#!/bin/env python
import sys
import pickle
from pprint import pprint

def unpickle(filename: str) -> list:
    objects = []
    with (open(filename, 'rb')) as openfile:
        while True:
            try:
                objects.append(pickle.load(openfile))
            except EOFError:
                break
    return objects


def main():
    if len(sys.argv) != 2:
        return print(f'Usage: {__file__} <file.pickle>')

    filename = sys.argv[1]
    objects = unpickle(filename)
    pprint(objects)


if __name__ == '__main__':
    main()
